import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul className='flex items-center justify-center gap-5 p-5 font-bold text-blue-600'>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/Add">Add News</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
